# libs.versions.toml

[versions]
activityCompose = "1.8.1"
appCompat = "1.6.1"
composeBom = "2023.03.00"
composeMaterial = "1.5.4"
composeMaterial3 = "1.2.0-alpha12"
composeUi = "1.0.0"
composeUiGraphics = "1.0.0"
composeUiToolingPreview = "1.0.0"
coreKtx = "1.12.0"
lifecycleRuntimeKtx = "2.6.2"
material = "1.10.0"
junit = "4.13.2"

[libraries]

# Core Libraries
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# AndroidX AppCompat
app-compat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }

# Google Material Components
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#AndroidX Lifecycle
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Jetpack Compose
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeUiGraphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeUiToolingPreview" }

# Material Design for Jetpack Compose
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeMaterial" }
compose-material3 = { group = "androidx.compose.material3", name = "material3-android", version.ref = "composeMaterial3" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
